/**
 * Types will be responsible to gather all the types that we can use in our reducers
 * the types are used to call the actions and make the interactions with the backend
 */
export const ADD_ALERTA = "ADD_ALERTA";
export const REMOVER_ALERTA = "REMOVER_ALERTA";
export const SUCESSO_REGISTRO_USUARIO = "SUCESSO_REGISTRO_USUARIO";
export const FALHA_REGISTRO_USUARIO = "FALHA_REGISTRO_USUARIO";
export const USUARIO_LOGADO = "USUARIO_LOGADO";
export const ERRO_AUTENTICACAO = "ERRO_AUTENTICACAO";
export const SUCESSO_LOGIN = "SUCESSO_LOGIN";
export const FALHA_LOGIN = "FALHA_LOGIN";
export const LOGOUT = "LOGOUT";
export const SUCESSO_INSERIR_SUPRIMENTO = "SUCESSO_INSERIR_SUPRIMENTO";
export const FALHA_INSERIR_SUPRIMENTO = "FALHA_INSERIR_SUPRIMENTO";
export const OBTER_TODOS_SUPRIMENTOS = "OBTER_TODOS_SUPRIMENTOS";
export const FALHA_OBTER_TODOS_SUPRIMENTOS = "FALHA_OBTER_TODOS_SUPRIMENTOS";
export const OBTER_SUPRIMENTO = "OBTER_SUPRIMENTO";
export const FALHA_OBTER_SUPRIMENTO = "FALHA_OBTER_SUPRIMENTO";
export const SUCESSO_TROCA_TONER = "SUCESSO_TROCA_TONER";
export const FALHA_TROCA_TONER = "FALHA_TROCA_TONER";
export const SUCESSO_OBTER_IMPRESSORA = "SUCESSO_OBTER_IMPRESSORA";
export const FALHA_OBTER_IMPRESSORA = "FALHA_OBTER_IMPRESSORA";
export const SUCESSO_OBTER_TODAS_IMPRESSORAS =
  "SUCESSO_OBTER_TODAS_IMPRESSORAS";
export const FALHA_OBTER_TODAS_IMPRESSORAS = "FALHA_OBTER_TODAS_IMPRESSORAS";
export const SUCESSO_INSERIR_IMPRESSORA = "SUCESSO_INSERIR_IMPRESSORA";
export const FALHA_INSERIR_IMPRESSORA = "FALHA_INSERIR_IMPRESSORA";
